--------------------------------------------------------------------------------
Python version is v3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Python executable Path is D:\Other\Github_Self\excelPlay\venv\Scripts
--------------------------------------------------------------------------------
User Name is Pratik Jaiswal
User Account is impra
--------------------------------------------------------------------------------
Time Stamp is Saturday, Feb 08 2025, 23:14:21:771220, IST (GMT+0530)
--------------------------------------------------------------------------------
Git Summary is 709d05d;  (HEAD -> main, origin/main, origin/HEAD); 2025-01-31 09:20:40 +0530; imPratik <impratikjaiswal@gmail.com>; handling of single item in list / tuple
--------------------------------------------------------------------------------
pythonHelpers version is v5.2.4.dev5
--------------------------------------------------------------------------------
excelPlay version is v2.6.0
--------------------------------------------------------------------------------
----------------------------------------------------- unit_testing -----------------------------------------------------
test_case_data:
test_case_id: unit_testing
test_case_name: unit_testing
test_case_file_name: unit_testing.log
execution_mode: UNIT_TESTING
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is UNIT_TESTING
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 1
Time Stamp is: 08-02-2025 23:14:21.79
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"unit_testing"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 79, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    return process_all_data_types(files_list_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 79, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 35, in handle_data
    res = __handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 77, in __handle_data
    PhUtil.archive_files(source_files_dir=folder_path, archive_format=data.archive_output_format,
  File "D:\Other\Github_Self\excelPlay\venv\lib\site-packages\python_helpers\ph_util.py", line 2299, in archive_files
    return PhUtil.zip_and_clean_dir(source_files_dir=source_files_dir,
  File "D:\Other\Github_Self\excelPlay\venv\lib\site-packages\python_helpers\ph_util.py", line 2331, in zip_and_clean_dir
    files_list = cls.create_zip(zip_file_path, source_files_dir, keep_source_dir_in_zip=keep_source_dir_in_zip,
  File "D:\Other\Github_Self\excelPlay\venv\lib\site-packages\python_helpers\ph_util.py", line 2308, in create_zip
    with zipfile.ZipFile(zip_file_name, 'w', zipfile.ZIP_DEFLATED) as zip_file:
  File "D:\ProgramFiles\Python39\lib\zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'excel_play\\test\\logs\\TC_input_items_tuple_multi_w_output_folder\\Excel Worksheet1\\..\\Excel Worksheet1.zip'
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: xyz
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was UNIT_TESTING; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
--------------------------------------------------------- user ---------------------------------------------------------
test_case_data:
test_case_id: user
test_case_name: user
test_case_file_name: user.log
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 2
Time Stamp is: 08-02-2025 23:15:19.66
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"user"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- samples_list -----------------------------------------------------
test_case_data:
test_case_id: samples_list
test_case_name: samples_list
test_case_file_name: samples_list.log
execution_mode: SAMPLES_LIST
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is SAMPLES_LIST
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 3
Time Stamp is: 08-02-2025 23:15:22.46
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"samples_list"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was SAMPLES_LIST; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------------- dev ---------------------------------------------------------
test_case_data:
test_case_id: dev
test_case_name: dev
test_case_file_name: dev.log
execution_mode: DEV
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is DEV
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 4
Time Stamp is: 08-02-2025 23:15:25.96
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"dev"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was DEV; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- known_issues -----------------------------------------------------
test_case_data:
test_case_id: known_issues
test_case_name: known_issues
test_case_file_name: known_issues.log
execution_mode: KNOWN_ISSUES
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is KNOWN_ISSUES
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 5
Time Stamp is: 08-02-2025 23:15:27.14
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"known_issues"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was KNOWN_ISSUES; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
------------------------------------------------- unit_testing_external ------------------------------------------------
test_case_data:
test_case_id: unit_testing_external
test_case_name: unit_testing_external
test_case_file_name: unit_testing_external.log
execution_mode: UNIT_TESTING_EXTERNAL
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is UNIT_TESTING_EXTERNAL
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 6
Time Stamp is: 08-02-2025 23:15:28.51
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"unit_testing_external"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was UNIT_TESTING_EXTERNAL; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------------- all ---------------------------------------------------------
test_case_data:
test_case_id: all
test_case_name: all
test_case_file_name: all.log
execution_mode: ALL
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is ALL
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 7
Time Stamp is: 08-02-2025 23:15:29.53
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"all"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: xyz
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was ALL; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_no_param -----------------------------------------------------
test_case_data:
test_case_id: cli_no_param
test_case_name: cli_no_param
test_case_file_name: cli_no_param.log
batch_params: 
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 1
Time Stamp is: 08-02-2025 23:16:38.63
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_no_param"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
------------------------------------------------------ cli_--help ------------------------------------------------------
test_case_data:
test_case_id: cli_--help
test_case_name: cli_--help
test_case_file_name: cli_--help.log
batch_params: --help
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 2
Time Stamp is: 08-02-2025 23:16:41.02
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_--help"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
--------------------------------------------------- cli_input_file_0 ---------------------------------------------------
test_case_data:
test_case_id: cli_input_file_0
test_case_name: cli_input_file_0
test_case_file_name: cli_input_file_0.log
batch_params: "D:\Other\Github_Self\excelPlay\data\sample_data\Excel Worksheet2.xlsx"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 3
Time Stamp is: 08-02-2025 23:16:42.03
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_input_file_0"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
--------------------------------------------------- cli_input_file_1 ---------------------------------------------------
test_case_data:
test_case_id: cli_input_file_1
test_case_name: cli_input_file_1
test_case_file_name: cli_input_file_1.log
batch_params: D:\Other\Github_Self\excelPlay\data\sample_data\Excel Worksheet2.xlsx
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 4
Time Stamp is: 08-02-2025 23:16:43.95
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_input_file_1"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 79, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: D:\Other\Github_Self\excelPlay\data\sample_data\Excel
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
--------------------------------------------------- cli_input_file_2 ---------------------------------------------------
test_case_data:
test_case_id: cli_input_file_2
test_case_name: cli_input_file_2
test_case_file_name: cli_input_file_2.log
batch_params: D:\Other\Github_Self\excelPlay\data\sample_data\Excel Worksheet2.xlsx
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 5
Time Stamp is: 08-02-2025 23:16:45.03
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_input_file_2"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 79, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: D:\Other\Github_Self\excelPlay\data\sample_data\Excel
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
--------------------------------------------------- cli_input_file_3 ---------------------------------------------------
test_case_data:
test_case_id: cli_input_file_3
test_case_name: cli_input_file_3
test_case_file_name: cli_input_file_3.log
batch_params: D:/Other/Github_Self/excelPlay/data/sample_data/Excel Worksheet2.xlsx
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 6
Time Stamp is: 08-02-2025 23:16:46.04
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_input_file_3"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 79, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: D:/Other/Github_Self/excelPlay/data/sample_data/Excel
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
--------------------------------------------------- cli_input_file_4 ---------------------------------------------------
test_case_data:
test_case_id: cli_input_file_4
test_case_name: cli_input_file_4
test_case_file_name: cli_input_file_4.log
batch_params: D:\Other\Github_Self\excelPlay\data\sample_data\Excel Worksheet2.xlsx
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 7
Time Stamp is: 08-02-2025 23:16:47.14
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_input_file_4"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 79, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: D:\Other\Github_Self\excelPlay\data\sample_data\Excel
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
--------------------------------------------------- cli_input_file_5 ---------------------------------------------------
test_case_data:
test_case_id: cli_input_file_5
test_case_name: cli_input_file_5
test_case_file_name: cli_input_file_5.log
batch_params: D:\Other\Github_Self\excelPlay\data\sample_data\Excel Worksheet2.xlsx
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 8
Time Stamp is: 08-02-2025 23:16:48.27
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_input_file_5"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 79, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: D:\Other\Github_Self\excelPlay\data\sample_data\Excel
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_0 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_0
test_case_name: cli_read_me_0
test_case_file_name: cli_read_me_0.log
batch_params: "file_path"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 9
Time Stamp is: 08-02-2025 23:16:49.34
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_0"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_1 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_1
test_case_name: cli_read_me_1
test_case_file_name: cli_read_me_1.log
batch_params: "data\sample_data\Excel Worksheet1.xlsx"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 10
Time Stamp is: 08-02-2025 23:16:50.40
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_1"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_2 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_2
test_case_name: cli_read_me_2
test_case_file_name: cli_read_me_2.log
batch_params: "data\sample_data\Excel Worksheet1.xlsxdata\sample_data\Excel Worksheet2.xlsx"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 11
Time Stamp is: 08-02-2025 23:16:54.04
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_2"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: data\sample_data\Excel Worksheet1.xlsxdata\sample_data\Excel Worksheet2.xlsx
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_3 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_3
test_case_name: cli_read_me_3
test_case_file_name: cli_read_me_3.log
batch_params: "data\sample_data"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 12
Time Stamp is: 08-02-2025 23:16:55.22
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_3"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_4 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_4
test_case_name: cli_read_me_4
test_case_file_name: cli_read_me_4.log
batch_params: "D:\Other\Github_Self\excelPlay\data\sample_data\Excel Worksheet1.xlsx"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 13
Time Stamp is: 08-02-2025 23:16:58.59
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_4"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_5 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_5
test_case_name: cli_read_me_5
test_case_file_name: cli_read_me_5.log
batch_params: "D:\Other\Github_Self\excelPlay\data\sample_data"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 14
Time Stamp is: 08-02-2025 23:17:00.36
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_5"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_6 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_6
test_case_name: cli_read_me_6
test_case_file_name: cli_read_me_6.log
batch_params: "D:\Other\Github_Self\excelPlay\data\sample_data\Excel Worksheet1.xlsx"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 15
Time Stamp is: 08-02-2025 23:17:03.63
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_6"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_7 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_7
test_case_name: cli_read_me_7
test_case_file_name: cli_read_me_7.log
batch_params: "D:/Other/Github_Self/excelPlay/data/sample_data/Excel Worksheet1.xlsx"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 16
Time Stamp is: 08-02-2025 23:17:05.44
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_7"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_8 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_8
test_case_name: cli_read_me_8
test_case_file_name: cli_read_me_8.log
batch_params: "file_path"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 17
Time Stamp is: 08-02-2025 23:17:08.21
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_8"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_read_me_9 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_9
test_case_name: cli_read_me_9
test_case_file_name: cli_read_me_9.log
batch_params: "dir_path"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 18
Time Stamp is: 08-02-2025 23:17:09.35
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_9"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: dir_path
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_10 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_10
test_case_name: cli_read_me_10
test_case_file_name: cli_read_me_10.log
batch_params: "file_path -f .csv"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 19
Time Stamp is: 08-02-2025 23:17:11.06
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_10"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -f .csv
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_11 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_11
test_case_name: cli_read_me_11
test_case_file_name: cli_read_me_11.log
batch_params: "file_path --output_format .csv"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 20
Time Stamp is: 08-02-2025 23:17:12.29
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_11"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --output_format .csv
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_12 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_12
test_case_name: cli_read_me_12
test_case_file_name: cli_read_me_12.log
batch_params: "file_path -f .xlsx"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 21
Time Stamp is: 08-02-2025 23:17:13.53
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_12"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -f .xlsx
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_13 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_13
test_case_name: cli_read_me_13
test_case_file_name: cli_read_me_13.log
batch_params: "file_path -ff .zip"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 22
Time Stamp is: 08-02-2025 23:17:14.68
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_13"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -ff .zip
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_14 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_14
test_case_name: cli_read_me_14
test_case_file_name: cli_read_me_14.log
batch_params: "file_path --archive_output_format .zip"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 23
Time Stamp is: 08-02-2025 23:17:15.77
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_14"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --archive_output_format .zip
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_15 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_15
test_case_name: cli_read_me_15
test_case_file_name: cli_read_me_15.log
batch_params: "file_path -a False"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 24
Time Stamp is: 08-02-2025 23:17:17.01
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_15"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -a False
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_16 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_16
test_case_name: cli_read_me_16
test_case_file_name: cli_read_me_16.log
batch_params: "file_path --archive_output True"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 25
Time Stamp is: 08-02-2025 23:17:18.78
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_16"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --archive_output True
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_17 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_17
test_case_name: cli_read_me_17
test_case_file_name: cli_read_me_17.log
batch_params: "file_path --archive_output true"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 26
Time Stamp is: 08-02-2025 23:17:19.91
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_17"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --archive_output true
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_18 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_18
test_case_name: cli_read_me_18
test_case_file_name: cli_read_me_18.log
batch_params: "file_path --archive_output yes"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 27
Time Stamp is: 08-02-2025 23:17:21.02
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_18"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --archive_output yes
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_19 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_19
test_case_name: cli_read_me_19
test_case_file_name: cli_read_me_19.log
batch_params: "file_path -o Test"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 28
Time Stamp is: 08-02-2025 23:17:22.16
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_19"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -o Test
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_20 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_20
test_case_name: cli_read_me_20
test_case_file_name: cli_read_me_20.log
batch_params: "file_path --output_path Test"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 29
Time Stamp is: 08-02-2025 23:17:23.29
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_20"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --output_path Test
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_21 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_21
test_case_name: cli_read_me_21
test_case_file_name: cli_read_me_21.log
batch_params: "file_path -e ascii"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 30
Time Stamp is: 08-02-2025 23:17:24.31
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_21"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -e ascii
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_22 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_22
test_case_name: cli_read_me_22
test_case_file_name: cli_read_me_22.log
batch_params: "file_path --encoding ascii"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 31
Time Stamp is: 08-02-2025 23:17:25.42
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_22"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --encoding ascii
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_23 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_23
test_case_name: cli_read_me_23
test_case_file_name: cli_read_me_23.log
batch_params: "file_path -ee replace"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 32
Time Stamp is: 08-02-2025 23:17:26.64
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_23"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -ee replace
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_24 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_24
test_case_name: cli_read_me_24
test_case_file_name: cli_read_me_24.log
batch_params: "file_path --encoding_errors replace"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 33
Time Stamp is: 08-02-2025 23:17:27.68
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_24"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 108, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 182, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 127, in process_all_data_types
    handle_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 34, in handle_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --encoding_errors replace
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------- cli_read_me_25 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_25
test_case_name: cli_read_me_25
test_case_file_name: cli_read_me_25.log
batch_params: "--help"
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 34
Time Stamp is: 08-02-2025 23:17:28.83
impra
PJ-LEGION

Microsoft Windows [Version 10.0.19045.5371]




"cli_read_me_25"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
