--------------------------------------------------------------------------------
Python version is v3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Python executable Path is D:\Other\Github_Self\excelPlay\venv\Scripts
--------------------------------------------------------------------------------
User Name is Pratik Jaiswal
User Account is impra
--------------------------------------------------------------------------------
Time Stamp is Monday, Nov 11 2024, 00:13:58:040063, IST (GMT+0530)
--------------------------------------------------------------------------------
Git Summary is 566c244;  (HEAD -> main, tag: v2.4.6, origin/main, origin/HEAD); 2024-10-31 20:59:48 +0530; imPratik <impratikjaiswal@gmail.com>; variable names corrections
--------------------------------------------------------------------------------
pythonHelpers version is v5.0.0
--------------------------------------------------------------------------------
excelPlay version is v2.5.0
--------------------------------------------------------------------------------
----------------------------------------------------- unit_testing -----------------------------------------------------
test_case_data:
test_case_id: unit_testing
test_case_name: unit_testing
test_case_file_name: unit_testing.log
execution_mode: UNIT_TESTING
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is UNIT_TESTING
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 1
Time Stamp is: 11-11-2024  0:13:58.09
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"unit_testing"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: xyz
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was UNIT_TESTING; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
--------------------------------------------------------- user ---------------------------------------------------------
test_case_data:
test_case_id: user
test_case_name: user
test_case_file_name: user.log
execution_mode: USER
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 2
Time Stamp is: 11-11-2024  0:15:09.33
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"user"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- samples_list -----------------------------------------------------
test_case_data:
test_case_id: samples_list
test_case_name: samples_list
test_case_file_name: samples_list.log
execution_mode: SAMPLES_LIST
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is SAMPLES_LIST
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 3
Time Stamp is: 11-11-2024  0:15:13.31
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"samples_list"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was SAMPLES_LIST; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------------- dev ---------------------------------------------------------
test_case_data:
test_case_id: dev
test_case_name: dev
test_case_file_name: dev.log
execution_mode: DEV
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is DEV
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 4
Time Stamp is: 11-11-2024  0:15:17.87
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"dev"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was DEV; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
------------------------------------------------- unit_testing_external ------------------------------------------------
test_case_data:
test_case_id: unit_testing_external
test_case_name: unit_testing_external
test_case_file_name: unit_testing_external.log
execution_mode: UNIT_TESTING_EXTERNAL
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is UNIT_TESTING_EXTERNAL
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 5
Time Stamp is: 11-11-2024  0:15:19.72
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"unit_testing_external"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was UNIT_TESTING_EXTERNAL; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
---------------------------------------------------------- all ---------------------------------------------------------
test_case_data:
test_case_id: all
test_case_name: all
test_case_file_name: all.log
execution_mode: ALL
error_handling_mode: CONTINUE_ON_ERROR
top_folder_path: []

*********************************************** update_variables_in_file ***********************************************
execution_mode: value_original was USER; target_value is ALL
top_folder_path: value_original was [os.pardir, os.pardir]; target_value is []
Executing "run_tc.bat"
Iteration 6
Time Stamp is: 11-11-2024  0:15:21.39
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"all"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: xyz
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
******************************************************* clean_up *******************************************************
execution_mode: value_original was ALL; target_value is USER
top_folder_path: value_original was []; target_value is [os.pardir, os.pardir]
----------------------------------------------------- cli_no_param -----------------------------------------------------
test_case_data:
test_case_id: cli_no_param
test_case_name: cli_no_param
test_case_file_name: cli_no_param.log
batch_params: 

Executing "run_tc.bat"
Iteration 1
Time Stamp is: 11-11-2024  0:16:25.59
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_no_param"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
------------------------------------------------------ cli_--help ------------------------------------------------------
test_case_data:
test_case_id: cli_--help
test_case_name: cli_--help
test_case_file_name: cli_--help.log
batch_params: --help

Executing "run_tc.bat"
Iteration 2
Time Stamp is: 11-11-2024  0:16:29.52
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_--help"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
--------------------------------------------------- cli_input_file_1 ---------------------------------------------------
test_case_data:
test_case_id: cli_input_file_1
test_case_name: cli_input_file_1
test_case_file_name: cli_input_file_1.log
batch_params: D:\Other\Github_Self\excelPlay\data\sampleData\Excel Worksheet2.xlsx

Executing "run_tc.bat"
Iteration 3
Time Stamp is: 11-11-2024  0:16:31.29
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_input_file_1"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: D:\Other\Github_Self\excelPlay\data\sampleData\Excel
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
--------------------------------------------------- cli_input_file_2 ---------------------------------------------------
test_case_data:
test_case_id: cli_input_file_2
test_case_name: cli_input_file_2
test_case_file_name: cli_input_file_2.log
batch_params: "D:\Other\Github_Self\excelPlay\data\sampleData\Excel Worksheet2.xlsx"

Executing "run_tc.bat"
Iteration 4
Time Stamp is: 11-11-2024  0:16:33.05
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_input_file_2"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_0 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_0
test_case_name: cli_read_me_0
test_case_file_name: cli_read_me_0.log
batch_params: "file_path"

Executing "run_tc.bat"
Iteration 5
Time Stamp is: 11-11-2024  0:16:36.37
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_0"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_1 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_1
test_case_name: cli_read_me_1
test_case_file_name: cli_read_me_1.log
batch_params: "data\sampleData\Excel Worksheet1.xlsx"

Executing "run_tc.bat"
Iteration 6
Time Stamp is: 11-11-2024  0:16:38.80
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_1"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_2 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_2
test_case_name: cli_read_me_2
test_case_file_name: cli_read_me_2.log
batch_params: "data\sampleData\Excel Worksheet1.xlsxdata\sampleData\Excel Worksheet2.xlsx"

Executing "run_tc.bat"
Iteration 7
Time Stamp is: 11-11-2024  0:16:41.54
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_2"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: data\sampleData\Excel Worksheet1.xlsxdata\sampleData\Excel Worksheet2.xlsx
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_3 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_3
test_case_name: cli_read_me_3
test_case_file_name: cli_read_me_3.log
batch_params: "data\sampleData"

Executing "run_tc.bat"
Iteration 8
Time Stamp is: 11-11-2024  0:16:43.42
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_3"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_4 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_4
test_case_name: cli_read_me_4
test_case_file_name: cli_read_me_4.log
batch_params: "D:\Other\Github_Self\excelPlay\data\sampleData\Excel Worksheet1.xlsx"

Executing "run_tc.bat"
Iteration 9
Time Stamp is: 11-11-2024  0:16:47.05
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_4"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_5 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_5
test_case_name: cli_read_me_5
test_case_file_name: cli_read_me_5.log
batch_params: "D:\Other\Github_Self\excelPlay\data\sampleData"

Executing "run_tc.bat"
Iteration 10
Time Stamp is: 11-11-2024  0:16:49.54
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_5"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_6 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_6
test_case_name: cli_read_me_6
test_case_file_name: cli_read_me_6.log
batch_params: "D:\Other\Github_Self\excelPlay\data\sampleData\Excel Worksheet1.xlsx"

Executing "run_tc.bat"
Iteration 11
Time Stamp is: 11-11-2024  0:16:55.63
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_6"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_7 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_7
test_case_name: cli_read_me_7
test_case_file_name: cli_read_me_7.log
batch_params: "D:/Other/Github_Self/excelPlay/data/sampleData/Excel Worksheet1.xlsx"

Executing "run_tc.bat"
Iteration 12
Time Stamp is: 11-11-2024  0:16:58.93
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_7"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_8 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_8
test_case_name: cli_read_me_8
test_case_file_name: cli_read_me_8.log
batch_params: "file_path"

Executing "run_tc.bat"
Iteration 13
Time Stamp is: 11-11-2024  0:17:01.76
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_8"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
----------------------------------------------------- cli_read_me_9 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_9
test_case_name: cli_read_me_9
test_case_file_name: cli_read_me_9.log
batch_params: "dir_path"

Executing "run_tc.bat"
Iteration 14
Time Stamp is: 11-11-2024  0:17:04.42
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_9"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: dir_path
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_10 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_10
test_case_name: cli_read_me_10
test_case_file_name: cli_read_me_10.log
batch_params: "file_path -f .csv"

Executing "run_tc.bat"
Iteration 15
Time Stamp is: 11-11-2024  0:17:06.34
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_10"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -f .csv
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_11 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_11
test_case_name: cli_read_me_11
test_case_file_name: cli_read_me_11.log
batch_params: "file_path --output_format .csv"

Executing "run_tc.bat"
Iteration 16
Time Stamp is: 11-11-2024  0:17:07.78
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_11"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --output_format .csv
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_12 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_12
test_case_name: cli_read_me_12
test_case_file_name: cli_read_me_12.log
batch_params: "file_path -f .xlsx"

Executing "run_tc.bat"
Iteration 17
Time Stamp is: 11-11-2024  0:17:09.06
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_12"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -f .xlsx
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_13 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_13
test_case_name: cli_read_me_13
test_case_file_name: cli_read_me_13.log
batch_params: "file_path -ff .zip"

Executing "run_tc.bat"
Iteration 18
Time Stamp is: 11-11-2024  0:17:10.69
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_13"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -ff .zip
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_14 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_14
test_case_name: cli_read_me_14
test_case_file_name: cli_read_me_14.log
batch_params: "file_path --archive_output_format .zip"

Executing "run_tc.bat"
Iteration 19
Time Stamp is: 11-11-2024  0:17:12.19
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_14"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --archive_output_format .zip
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_15 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_15
test_case_name: cli_read_me_15
test_case_file_name: cli_read_me_15.log
batch_params: "file_path -a False"

Executing "run_tc.bat"
Iteration 20
Time Stamp is: 11-11-2024  0:17:13.47
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_15"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -a False
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_16 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_16
test_case_name: cli_read_me_16
test_case_file_name: cli_read_me_16.log
batch_params: "file_path --archive_output True"

Executing "run_tc.bat"
Iteration 21
Time Stamp is: 11-11-2024  0:17:14.95
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_16"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --archive_output True
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_17 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_17
test_case_name: cli_read_me_17
test_case_file_name: cli_read_me_17.log
batch_params: "file_path --archive_output true"

Executing "run_tc.bat"
Iteration 22
Time Stamp is: 11-11-2024  0:17:16.30
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_17"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --archive_output true
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_18 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_18
test_case_name: cli_read_me_18
test_case_file_name: cli_read_me_18.log
batch_params: "file_path --archive_output yes"

Executing "run_tc.bat"
Iteration 23
Time Stamp is: 11-11-2024  0:17:17.56
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_18"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --archive_output yes
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_19 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_19
test_case_name: cli_read_me_19
test_case_file_name: cli_read_me_19.log
batch_params: "file_path -o Test"

Executing "run_tc.bat"
Iteration 24
Time Stamp is: 11-11-2024  0:17:18.83
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_19"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -o Test
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_20 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_20
test_case_name: cli_read_me_20
test_case_file_name: cli_read_me_20.log
batch_params: "file_path --output_path Test"

Executing "run_tc.bat"
Iteration 25
Time Stamp is: 11-11-2024  0:17:20.17
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_20"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --output_path Test
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_21 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_21
test_case_name: cli_read_me_21
test_case_file_name: cli_read_me_21.log
batch_params: "file_path -e ascii"

Executing "run_tc.bat"
Iteration 26
Time Stamp is: 11-11-2024  0:17:21.67
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_21"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -e ascii
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_22 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_22
test_case_name: cli_read_me_22
test_case_file_name: cli_read_me_22.log
batch_params: "file_path --encoding ascii"

Executing "run_tc.bat"
Iteration 27
Time Stamp is: 11-11-2024  0:17:23.36
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_22"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --encoding ascii
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_23 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_23
test_case_name: cli_read_me_23
test_case_file_name: cli_read_me_23.log
batch_params: "file_path -ee replace"

Executing "run_tc.bat"
Iteration 28
Time Stamp is: 11-11-2024  0:17:24.70
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_23"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path -ee replace
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_24 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_24
test_case_name: cli_read_me_24
test_case_file_name: cli_read_me_24.log
batch_params: "file_path --encoding_errors replace"

Executing "run_tc.bat"
Iteration 29
Time Stamp is: 11-11-2024  0:17:26.68
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_24"
Attempting to activate existing Virtual Environment
Traceback (most recent call last):
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 104, in process_safe
    self.__process_safe_individual(data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\data_type\data_type_master.py", line 176, in __process_safe_individual
    process_all_data_types(data, meta_data, info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 57, in process_all_data_types
    parsed_data_list.append(process_all_data_types(sub_data))
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\parser.py", line 99, in process_all_data_types
    process_data(data=data, meta_data=meta_data, info_data=info_data)
  File "D:\Other\Github_Self\excelPlay\excel_play\main\convert\handler.py", line 78, in process_data
    raise FileNotFoundError(f'Invalid Path: {data.input_data}')
FileNotFoundError: Invalid Path: file_path --encoding_errors replace
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
---------------------------------------------------- cli_read_me_25 ----------------------------------------------------
test_case_data:
test_case_id: cli_read_me_25
test_case_name: cli_read_me_25
test_case_file_name: cli_read_me_25.log
batch_params: "--help"

Executing "run_tc.bat"
Iteration 30
Time Stamp is: 11-11-2024  0:17:28.36
impra
LAPTOP-AO84OQO2

Microsoft Windows [Version 10.0.19045.5011]




"cli_read_me_25"
Attempting to activate existing Virtual Environment
Attempting to deactivate existing (and activated) Virtual Environment




"Batch Execution Done"
